### **Data Preprocessing**

In [ ]:
# Importing Python packages
import pandas as pd                                              # For data manipulation and analysis
import numpy as np                                               # For numerical operations
import seaborn as sns                                            # For data visualization
import matplotlib.pyplot as plt                                  # For creating visualizations

# To ignore warnings
import warnings                                                  # To handle warnings
warnings.filterwarnings("ignore")                                # Suppress all warnings

In [ ]:
# Import dataset
synthetic_insurance_data = pd.read_csv('/content/drive/MyDrive/Actuarial Project/synthetic_insurance_data.csv')

synthetic_insurance_data.head()

,Age,Is_Senior,Marital_Status,Married_Premium_Discount,Prior_Insurance,Prior_Insurance_Premium_Adjustment,Claims_Frequency,Claims_Severity,Claims_Adjustment,Policy_Type,...,Time_Since_First_Contact,Conversion_Status,Website_Visits,Inquiries,Quotes_Requested,Time_to_Conversion,Credit_Score,Premium_Adjustment_Credit,Region,Premium_Adjustment_Region
0,47,0,Married,86,1-5 years,50,0,Low,0,Full Coverage,...,10,0,5,1,2,99,704,-50,Suburban,50
1,37,0,Married,86,1-5 years,50,0,Low,0,Full Coverage,...,22,0,5,1,2,99,726,-50,Urban,100
2,49,0,Married,86,1-5 years,50,1,Low,50,Full Coverage,...,28,0,4,4,1,99,772,-50,Urban,100
3,62,1,Married,86,>5 years,0,1,Low,50,Full Coverage,...,4,1,6,2,2,2,809,-50,Urban,100
4,36,0,Single,0,>5 years,0,2,Low,100,Full Coverage,...,14,1,8,4,2,10,662,50,Suburban,50

In [ ]:
# Checking the shape of the data
synthetic_insurance_data.shape

(10000, 27)

In [ ]:
# Checking basic info about the data
synthetic_insurance_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 27 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Age                                 10000 non-null  int64
 1   Is_Senior                           10000 non-null  int64
 2   Marital_Status                      10000 non-null  object
 3   Married_Premium_Discount            10000 non-null  int64
 4   Prior_Insurance                     10000 non-null  object
 5   Prior_Insurance_Premium_Adjustment  10000 non-null  int64
 6   Claims_Frequency                    10000 non-null  int64
 7   Claims_Severity                     10000 non-null  object
 8   Claims_Adjustment                   10000 non-null  int64
 9   Policy_Type                         10000 non-null  object
 10  Policy_Adjustment                   10000 non-null  int64
 11  Premium_Amount                      10000 non-null  int64
 12  Safe_Driver_Discount                10000 non-null  int64
 13  Multi_Policy_Discount               10000 non-null  int64
 14  Bundling_Discount                   10000 non-null  int64
 15  Total_Discounts                     10000 non-null  int64
 16  Source_of_Lead                      10000 non-null  object
 17  Time_Since_First_Contact            10000 non-null  int64
 18  Conversion_Status                   10000 non-null  int64
 19  Website_Visits                      10000 non-null  int64
 20  Inquiries                           10000 non-null  int64
 21  Quotes_Requested                    10000 non-null  int64
 22  Time_to_Conversion                  10000 non-null  int64
 23  Credit_Score                        10000 non-null  int64
 24  Premium_Adjustment_Credit           10000 non-null  int64
 25  Region                              10000 non-null  object
 26  Premium_Adjustment_Region           10000 non-null  int64
dtypes: int64(21), object(6)
memory usage: 2.1+ MB

In [ ]:
# Checking the description of the numerical features of the data
synthetic_insurance_data.describe()

,Age,Is_Senior,Married_Premium_Discount,Prior_Insurance_Premium_Adjustment,Claims_Frequency,Claims_Adjustment,Policy_Adjustment,Premium_Amount,Safe_Driver_Discount,Multi_Policy_Discount,...,Total_Discounts,Time_Since_First_Contact,Conversion_Status,Website_Visits,Inquiries,Quotes_Requested,Time_to_Conversion,Credit_Score,Premium_Adjustment_Credit,Premium_Adjustment_Region
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,...,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,39.991700,0.159300,42.131400,47.625000,0.497200,36.780000,-79.860000,2219.571400,0.199900,0.305100,...,30.110000,15.478000,0.576700,5.022900,1.996900,1.996900,46.07320,714.253400,-11.320000,64.325000
std,14.050358,0.365974,42.993376,34.354438,0.716131,65.910288,97.955806,148.521132,0.399945,0.460473,...,33.689782,8.677975,0.494107,2.238231,1.415588,0.817409,45.44845,49.749487,48.704156,39.232618
min,18.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-200.000000,1800.000000,0.000000,0.000000,...,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.00000,530.000000,-50.000000,0.000000
25%,29.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-200.000000,2100.000000,0.000000,0.000000,...,0.000000,8.000000,0.000000,3.000000,1.000000,1.000000,6.00000,681.000000,-50.000000,50.000000
50%,39.000000,0.000000,0.000000,50.000000,0.000000,0.000000,0.000000,2236.000000,0.000000,0.000000,...,50.000000,16.000000,1.000000,5.000000,2.000000,2.000000,12.00000,715.000000,-50.000000,50.000000
75%,50.000000,0.000000,86.000000,50.000000,1.000000,50.000000,0.000000,2336.000000,0.000000,1.000000,...,50.000000,23.000000,1.000000,6.000000,3.000000,3.000000,99.00000,748.000000,50.000000,100.000000
max,90.000000,1.000000,86.000000,100.000000,5.000000,800.000000,0.000000,2936.000000,1.000000,1.000000,...,150.000000,30.000000,1.000000,16.000000,9.000000,3.000000,99.00000,850.000000,50.000000,100.000000

In [ ]:
# Converting Is_Senior from numerical to categorical column

synthetic_insurance_data["Is_Senior"] = synthetic_insurance_data["Is_Senior"].replace({1: "Senior", 0: "Non-Senior"})

In [ ]:
# Standardising Marital_Status categories

synthetic_insurance_data["Marital_Status"].unique()

array(['Married', 'Single', 'Widowed', 'Divorced'], dtype=object)

In [ ]:
# Standardising Prior_Insurance

synthetic_insurance_data["Prior_Insurance"].unique()

array(['1-5 years', '>5 years', '<1 year'], dtype=object)

In [ ]:
# Validating Claims_Frequency Field

# Quick stats
print(synthetic_insurance_data["Claims_Frequency"].describe())

# Check unique values
print(synthetic_insurance_data["Claims_Frequency"].unique())

# Check for negatives
print(synthetic_insurance_data.loc[synthetic_insurance_data["Claims_Frequency"] < 0, "Claims_Frequency"])

count    10000.000000
mean         0.497200
std          0.716131
min          0.000000
25%          0.000000
50%          0.000000
75%          1.000000
max          5.000000
Name: Claims_Frequency, dtype: float64
[0 1 2 3 4 5]
Series([], Name: Claims_Frequency, dtype: int64)

In [ ]:
# Validating Claims_Severity
synthetic_insurance_data["Claims_Severity"].unique()

array(['Low', 'Medium', 'High'], dtype=object)

In [ ]:
# Validating Claims_Adjustment Field

# Quick stats
print(synthetic_insurance_data["Claims_Adjustment"].describe())

# Check unique values
print(synthetic_insurance_data["Claims_Adjustment"].unique())

# Check for negatives
print(synthetic_insurance_data.loc[synthetic_insurance_data["Claims_Adjustment"] < 0, "Claims_Adjustment"])

count    10000.000000
mean        36.780000
std         65.910288
min          0.000000
25%          0.000000
50%          0.000000
75%         50.000000
max        800.000000
Name: Claims_Adjustment, dtype: float64
[  0  50 100 200 150 400 300 600 250 800]
Series([], Name: Claims_Adjustment, dtype: int64)

In [ ]:
# Validating Policy_Type
synthetic_insurance_data["Policy_Type"].unique()

array(['Full Coverage', 'Liability-Only'], dtype=object)

In [ ]:
# Validating Policy_Adjustment

# Quick stats
print(synthetic_insurance_data["Policy_Adjustment"].describe())

# Check unique values
print(synthetic_insurance_data["Policy_Adjustment"].unique())

# Check for negatives
print(synthetic_insurance_data.loc[synthetic_insurance_data["Policy_Adjustment"] < 0, "Policy_Adjustment"])

count    10000.000000
mean       -79.860000
std         97.955806
min       -200.000000
25%       -200.000000
50%          0.000000
75%          0.000000
max          0.000000
Name: Policy_Adjustment, dtype: float64
[   0 -200]
5      -200
8      -200
10     -200
11     -200
12     -200
       ...
9988   -200
9992   -200
9993   -200
9998   -200
9999   -200
Name: Policy_Adjustment, Length: 3993, dtype: int64

In [ ]:
# Validating Source_of_Lead categories

synthetic_insurance_data["Source_of_Lead"].unique()

array(['Agent', 'Online', 'Referral'], dtype=object)

In [ ]:
# Converting Conversion_Status from numerical to categorical column

synthetic_insurance_data["Conversion_Status"] = synthetic_insurance_data["Conversion_Status"].replace({1: "Converted", 0: "Not Converted"})

In [ ]:
# Validating Website_Visits

# Quick stats
print(synthetic_insurance_data["Website_Visits"].describe())

# Check unique values
print(synthetic_insurance_data["Website_Visits"].unique())

# Check for negatives
print(synthetic_insurance_data.loc[synthetic_insurance_data["Website_Visits"] < 0, "Website_Visits"])

count    10000.000000
mean         5.022900
std          2.238231
min          0.000000
25%          3.000000
50%          5.000000
75%          6.000000
max         16.000000
Name: Website_Visits, dtype: float64
[ 5  4  6  8  3  7  9  2  1 10  0 11 12 13 15 16 14]
Series([], Name: Website_Visits, dtype: int64)

In [ ]:
# Validating Inquiries

# Quick stats
print(synthetic_insurance_data["Inquiries"].describe())

# Check unique values
print(synthetic_insurance_data["Inquiries"].unique())

# Check for negatives
print(synthetic_insurance_data.loc[synthetic_insurance_data["Inquiries"] < 0, "Inquiries"])

count    10000.000000
mean         1.996900
std          1.415588
min          0.000000
25%          1.000000
50%          2.000000
75%          3.000000
max          9.000000
Name: Inquiries, dtype: float64
[1 4 2 0 3 5 6 7 8 9]
Series([], Name: Inquiries, dtype: int64)

In [ ]:
# Validating Quotes_Requested

# Quick stats
print(synthetic_insurance_data["Quotes_Requested"].describe())

# Check unique values
print(synthetic_insurance_data["Quotes_Requested"].unique())

# Check for negatives
print(synthetic_insurance_data.loc[synthetic_insurance_data["Quotes_Requested"] < 0, "Quotes_Requested"])

count    10000.000000
mean         1.996900
std          0.817409
min          1.000000
25%          1.000000
50%          2.000000
75%          3.000000
max          3.000000
Name: Quotes_Requested, dtype: float64
[2 1 3]
Series([], Name: Quotes_Requested, dtype: int64)

In [ ]:
# Replacing Time_of_Conversion of 99 to NaN

synthetic_insurance_data.loc[(synthetic_insurance_data["Conversion_Status"] == 0) & (synthetic_insurance_data["Time_to_Conversion"] == 99), "Time_to_Conversion"] = np.nan

In [ ]:
# Validate the basic stats and distribution to check for out of range scores

synthetic_insurance_data["Credit_Score"].describe()

count    10000.000000
mean       714.253400
std         49.749487
min        530.000000
25%        681.000000
50%        715.000000
75%        748.000000
max        850.000000
Name: Credit_Score, dtype: float64

In [ ]:
# Validating Premium_Adjustment_Credit

# Quick stats
print(synthetic_insurance_data["Premium_Adjustment_Credit"].describe())

# Check unique values
print(synthetic_insurance_data["Premium_Adjustment_Credit"].unique())

# Check for negatives
print(synthetic_insurance_data.loc[synthetic_insurance_data["Premium_Adjustment_Credit"] < 0, "Premium_Adjustment_Credit"])

count    10000.000000
mean       -11.320000
std         48.704156
min        -50.000000
25%        -50.000000
50%        -50.000000
75%         50.000000
max         50.000000
Name: Premium_Adjustment_Credit, dtype: float64
[-50  50]
0      -50
1      -50
2      -50
3      -50
5      -50
        ..
9992   -50
9993   -50
9994   -50
9995   -50
9999   -50
Name: Premium_Adjustment_Credit, Length: 6132, dtype: int64

In [ ]:
# Validating Region

# Quick stats
print(synthetic_insurance_data["Region"].describe())

# Check unique values
print(synthetic_insurance_data["Region"].unique())

count     10000
unique        3
top       Urban
freq       4921
Name: Region, dtype: object
['Suburban' 'Urban' 'Rural']

In [ ]:
# Validating Premium_Adjustment_Region

# Quick stats
print(synthetic_insurance_data["Premium_Adjustment_Region"].describe())

# Check unique values
print(synthetic_insurance_data["Premium_Adjustment_Region"].unique())

count    10000.000000
mean        64.325000
std         39.232618
min          0.000000
25%         50.000000
50%         50.000000
75%        100.000000
max        100.000000
Name: Premium_Adjustment_Region, dtype: float64
[ 50 100   0]

### Derived Features

#### Risk_Tier

In [ ]:
def risk_tier(row):
    freq = row["Claims_Frequency"]
    sev = row["Claims_Severity"]

    if freq >= 3 or sev == "High":
        return "High Risk"
    elif freq == 2 or sev == "Medium":
        return "Medium Risk"
    else:
        return "Low Risk"

synthetic_insurance_data["Risk_Tier"] = synthetic_insurance_data.apply(risk_tier, axis=1)

#### Loyalty_Band

In [ ]:
def loyalty_band(prior_insurance):
    if pd.isna(prior_insurance):
        return "Unknown"
    elif prior_insurance == "<1 year":
        return "New Customer"
    elif prior_insurance == "1-5 years":
        return "1–5 Years"
    elif prior_insurance == ">5 years":
        return ">5 Years"
    else:
        return "Other"

synthetic_insurance_data["Loyalty_Band"] = synthetic_insurance_data["Prior_Insurance"].apply(loyalty_band)

#### Engagement Level

In [ ]:
# Weighted engagement score

synthetic_insurance_data["Engagement_Score"] = (
    synthetic_insurance_data["Website_Visits"] +
    2 * synthetic_insurance_data["Inquiries"] +
    3 * synthetic_insurance_data["Quotes_Requested"]
)

# Classify into bands
def engagement_level(score):
    if score <= 5:
        return "Low Engagement"
    elif score <= 15:
        return "Medium Engagement"
    else:
        return "High Engagement"

synthetic_insurance_data["Engagement_Level"] = synthetic_insurance_data["Engagement_Score"].apply(engagement_level)

In [ ]:
# Validating the changes made to dataset.

synthetic_insurance_data.head()

,Age,Is_Senior,Marital_Status,Married_Premium_Discount,Prior_Insurance,Prior_Insurance_Premium_Adjustment,Claims_Frequency,Claims_Severity,Claims_Adjustment,Policy_Type,...,Quotes_Requested,Time_to_Conversion,Credit_Score,Premium_Adjustment_Credit,Region,Premium_Adjustment_Region,Risk_Tier,Loyalty_Band,Engagement_Score,Engagement_Level
0,47,Non-Senior,Married,86,1-5 years,50,0,Low,0,Full Coverage,...,2,99.0,704,-50,Suburban,50,Low Risk,1–5 Years,13,Medium Engagement
1,37,Non-Senior,Married,86,1-5 years,50,0,Low,0,Full Coverage,...,2,99.0,726,-50,Urban,100,Low Risk,1–5 Years,13,Medium Engagement
2,49,Non-Senior,Married,86,1-5 years,50,1,Low,50,Full Coverage,...,1,99.0,772,-50,Urban,100,Low Risk,1–5 Years,15,Medium Engagement
3,62,Senior,Married,86,>5 years,0,1,Low,50,Full Coverage,...,2,2.0,809,-50,Urban,100,Low Risk,>5 Years,16,High Engagement
4,36,Non-Senior,Single,0,>5 years,0,2,Low,100,Full Coverage,...,2,10.0,662,50,Suburban,50,Medium Risk,>5 Years,22,High Engagement

### Saving cleaned dataset for further analysis.

In [ ]:
from google.colab import files

# Save to Colab filesystem
synthetic_insurance_data.to_csv("cleaned_insurance_data.csv", index=False)

# Download to your local machine
files.download("cleaned_insurance_data.csv")